### ISSUE TITLE
Prompt for first- and last name triggers numeric keyboard - ffos2.0

### ISSUE THREAD

**Issue by Artox** [justapps4all/connected-im#17]
After entering the confirmation sms code, a prompt is opened asking about first and last name.
These textboxes only open the numeric keyboard on my phone which doesn't make any sense and forces me to enter a number for my name

Alcatel OneTouch Fire E (FFOS-2.0)

**Comment by justapps4all** [comment]
Thank you very much for you issue. We really appreciate it.

It should be fixed right now.

All the best!!
